2022-02-16 16:11:35,350 INFO    MainThread:2562880 [wandb_setup.py:_flush():71] setting env: {}
2022-02-16 16:11:35,351 INFO    MainThread:2562880 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-16 16:11:35,351 INFO    MainThread:2562880 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-16 16:11:35,351 INFO    MainThread:2562880 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\aar245\Desktop\privacy_preserving_nn\src_3\wandb\run-20220216_161135-344ythm2\logs\debug.log
2022-02-16 16:11:35,351 INFO    MainThread:2562880 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\aar245\Desktop\privacy_preserving_nn\src_3\wandb\run-20220216_161135-344ythm2\logs\debug-internal.log
2022-02-16 16:11:35,389 INFO    MainThread:2562880 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001F8968C6550>
2022-02-16 16:11:35,390 INFO    MainThread:2562880 [wandb_init.py:init():404] calling init triggers
2022-02-16 16:11:35,390 INFO    MainThread:2562880 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'appliance': 'refrigerator1', 'epochs': 10, 'batch_size': 150, 'learning_rate': 0.0003318089969908341, 'in_channels': 1, 'out_channels': 16, 'kernel_size': 7, 'hidden_size_1': 64, 'hidden_size_2': 85, 'fc1': 211, 'fc2': 109, 'weight_decay': 0, 'window_size': 499}
2022-02-16 16:11:35,390 INFO    MainThread:2562880 [wandb_init.py:init():460] starting backend
2022-02-16 16:11:35,390 INFO    MainThread:2562880 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-02-16 16:11:35,396 INFO    MainThread:2562880 [backend.py:ensure_launched():216] starting backend process...
2022-02-16 16:11:35,508 INFO    MainThread:2562880 [backend.py:ensure_launched():221] started backend process with pid: 2579232
2022-02-16 16:11:35,510 INFO    MainThread:2562880 [wandb_init.py:init():469] backend started and connected
2022-02-16 16:11:35,531 INFO    MainThread:2562880 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-16 16:11:35,532 INFO    MainThread:2562880 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-16 16:11:35,532 INFO    MainThread:2562880 [wandb_init.py:init():533] updated telemetry
2022-02-16 16:11:35,538 INFO    MainThread:2562880 [wandb_init.py:init():563] communicating current version
2022-02-16 16:11:37,491 INFO    MainThread:2562880 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-16 16:11:37,492 INFO    MainThread:2562880 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-16 16:11:37,658 INFO    MainThread:2562880 [wandb_init.py:init():606] starting run threads in backend
2022-02-16 16:11:42,668 INFO    MainThread:2562880 [wandb_run.py:_console_start():1810] atexit reg
2022-02-16 16:11:42,669 INFO    MainThread:2562880 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-16 16:11:42,669 INFO    MainThread:2562880 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-16 16:11:42,672 INFO    MainThread:2562880 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-16 16:11:42,673 INFO    MainThread:2562880 [wandb_init.py:init():633] run started, returning control to user process
2022-02-16 16:11:42,939 INFO    MainThread:2562880 [wandb_watch.py:watch():43] Watching
2022-02-16 16:15:30,990 INFO    MainThread:2562880 [wandb_run.py:finish():1457] finishing run nilm/global_models_feb10/344ythm2
2022-02-16 16:15:30,997 INFO    MainThread:2562880 [jupyter.py:save_history():458] saving 14 cells to _session_history.ipynb
2022-02-16 16:15:31,009 INFO    MainThread:2562880 [wandb_run.py:_config_callback():956] config_cb ('_wandb', 'session_history') code\_session_history.ipynb None
2022-02-16 16:15:31,044 INFO    MainThread:2562880 [jupyter.py:save_ipynb():377] looking for notebook: Desktop/privacy_preserving_nn/src_3/main.ipynb
2022-02-16 16:15:31,045 INFO    MainThread:2562880 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-16 16:15:31,045 INFO    MainThread:2562880 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-02-16 16:15:31,051 INFO    MainThread:2562880 [wandb_run.py:_restore():1752] restore
2022-02-16 16:15:31,282 INFO    MainThread:2562880 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 814
  total_bytes: 814
}

